# Generated by Django 4.2.5 on 2023-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=6
            ),
        ),
    ]
