# Generated by Django 4.2.5 on 2023-10-07 05:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0002_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 11, 21, 16, 32374)
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="subjects",
            field=models.ManyToManyField(blank=True, null=True, to="classroom.subject"),
        ),
    ]
