# Generated by Django 4.2.5 on 2023-10-07 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0003_alter_attendance_date_alter_class_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 12, 4, 26, 401287)
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Working Day", "Working Day"),
                    ("Non Working Day", "Non Working Day"),
                ],
                default="Working Day",
                max_length=25,
            ),
        ),
    ]
