# Generated by Django 4.2.5 on 2023-10-07 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0004_alter_attendance_date_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 12, 7, 29, 516022)
            ),
        ),
    ]
