# Generated by Django 4.2.5 on 2023-10-07 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0005_alter_attendance_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subject",
            old_name="grade",
            new_name="credit",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 12, 13, 51, 889837)
            ),
        ),
    ]
