# Generated by Django 4.2.5 on 2023-10-07 08:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0007_exam_alter_attendance_date_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 14, 17, 29, 785668)
            ),
        ),
        migrations.RemoveField(
            model_name="exam",
            name="class_id",
        ),
        migrations.AddField(
            model_name="exam",
            name="class_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classroom.class",
            ),
            preserve_default=False,
        ),
    ]
