# Generated by Django 4.2.5 on 2023-10-07 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0008_alter_attendance_date_remove_exam_class_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 14, 18, 29, 137124)
            ),
        ),
    ]
