# Generated by Django 4.2.5 on 2023-10-07 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0009_alter_attendance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="unique_field",
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 14, 25, 59, 804897)
            ),
        ),
    ]
