# Generated by Django 4.2.5 on 2023-10-07 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0010_exam_unique_field_alter_attendance_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="unique_field",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2023, 10, 7, 14, 34, 57, 444845)
            ),
        ),
    ]
