# Generated by Django 4.1 on 2023-11-10 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_attendance'),
        ('classroom', '0011_remove_exam_unique_field_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='classroom.subject'),
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='notes/')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.subject')),
            ],
        ),
    ]
