# Generated by Django 4.2.5 on 2023-11-10 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classroom", "0012_alter_attendance_date_alter_attendance_students_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="class",
            old_name="unique_field",
            new_name="class_id",
        ),
    ]
